<a href="https://colab.research.google.com/github/jihwanK/practice/blob/master/ch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
torch.tensor([[1, 1],[0, 0]])

tensor([[1, 1],
        [0, 0]])

In [3]:
torch.tensor([[1, 1],[0, 0]], device="cuda:0")

tensor([[1, 1],
        [0, 0]], device='cuda:0')

In [4]:
torch.tensor([[1, 1],[0, 0]], dtype=torch.float64)

tensor([[1., 1.],
        [0., 0.]], dtype=torch.float64)

In [5]:
tmp = torch.tensor([[1, 2],[3, 4]], device="cuda:0")

In [6]:
tmp

tensor([[1, 2],
        [3, 4]], device='cuda:0')

In [7]:
tmp = torch.tensor([[1, 2, 3],[4, 5, 6], [2, 1, 9], [4, 6, 2]])

In [8]:
tmp.shape

torch.Size([4, 3])

In [9]:
tmp.view(1, -1)

tensor([[1, 2, 3, 4, 5, 6, 2, 1, 9, 4, 6, 2]])

In [10]:
tmp.view(-1)

tensor([1, 2, 3, 4, 5, 6, 2, 1, 9, 4, 6, 2])

In [11]:
tmp.view(3, 2, -1)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [2, 1]],

        [[9, 4],
         [6, 2]]])

In [12]:
import pandas as pd

In [13]:
import torchvision

In [14]:
import torchvision.transforms as transforms

In [15]:
mnist_transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (1.0,))
])

In [16]:
from torchvision.datasets import MNIST
import requests

In [17]:
download_root = "../chap02/data/MNIST_DATASET"
train_dataset = MNIST(download_root, transform=mnist_transform, train=True, download=True)
valid_dataset = MNIST(download_root, transform=mnist_transform, train=False, download=True)
test_dataset = MNIST(download_root, transform=mnist_transform, train=False, download=True)

100%|██████████| 9912422/9912422 [00:00<00:00, 370229937.08it/s]

Extracting ../chap02/data/MNIST_DATASET/MNIST/raw/train-images-idx3-ubyte.gz to ../chap02/data/MNIST_DATASET/MNIST/raw


100%|██████████| 28881/28881 [00:00<00:00, 41584515.56it/s]


Extracting ../chap02/data/MNIST_DATASET/MNIST/raw/train-labels-idx1-ubyte.gz to ../chap02/data/MNIST_DATASET/MNIST/raw



100%|██████████| 1648877/1648877 [00:00<00:00, 56874106.88it/s]


Extracting ../chap02/data/MNIST_DATASET/MNIST/raw/t10k-images-idx3-ubyte.gz to ../chap02/data/MNIST_DATASET/MNIST/raw



100%|██████████| 4542/4542 [00:00<00:00, 17655726.38it/s]


Extracting ../chap02/data/MNIST_DATASET/MNIST/raw/t10k-labels-idx1-ubyte.gz to ../chap02/data/MNIST_DATASET/MNIST/raw

